name: flutter_earth_online

packages:
  - packages/*
  - packages/features/*
  - packages/shared/*
  - apps/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run flutter analyze in all packages

  test:
    run: melos exec -- flutter test
    description: Run flutter test in all packages

  build_runner:
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner in all packages

  clean:
    run: melos exec -- flutter clean
    description: Run flutter clean in all packages

  pub_get:
    run: melos exec -- flutter pub get
    description: Run flutter pub get in all packages
